// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetFeatureSupportsHandlerFunc turns a function with the right signature into a get feature supports handler
type GetFeatureSupportsHandlerFunc func(GetFeatureSupportsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFeatureSupportsHandlerFunc) Handle(params GetFeatureSupportsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetFeatureSupportsHandler interface for that can handle valid get feature supports params
type GetFeatureSupportsHandler interface {
	Handle(GetFeatureSupportsParams, interface{}) middleware.Responder
}

// NewGetFeatureSupports creates a new http.Handler for the get feature supports operation
func NewGetFeatureSupports(ctx *middleware.Context, handler GetFeatureSupportsHandler) *GetFeatureSupports {
	return &GetFeatureSupports{Context: ctx, Handler: handler}
}

/*
	GetFeatureSupports swagger:route GET /v2/support-levels/feature-supports installer getFeatureSupports

Retrieves the features support levels for each OpenShift version.
*/
type GetFeatureSupports struct {
	Context *middleware.Context
	Handler GetFeatureSupportsHandler
}

func (o *GetFeatureSupports) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFeatureSupportsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
