// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// GetFeatureSupportsURL generates an URL for the get feature supports operation
type GetFeatureSupportsURL struct {
	CPUArchitecture  *string
	FeatureIds       []string
	OpenshiftVersion string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetFeatureSupportsURL) WithBasePath(bp string) *GetFeatureSupportsURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetFeatureSupportsURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetFeatureSupportsURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/v2/support-levels/feature-supports"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api/assisted-install"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var cPUArchitectureQ string
	if o.CPUArchitecture != nil {
		cPUArchitectureQ = *o.CPUArchitecture
	}
	if cPUArchitectureQ != "" {
		qs.Set("cpu_architecture", cPUArchitectureQ)
	}

	var featureIdsIR []string
	for _, featureIdsI := range o.FeatureIds {
		featureIdsIS := featureIdsI
		if featureIdsIS != "" {
			featureIdsIR = append(featureIdsIR, featureIdsIS)
		}
	}

	featureIds := swag.JoinByFormat(featureIdsIR, "")

	if len(featureIds) > 0 {
		qsv := featureIds[0]
		if qsv != "" {
			qs.Set("feature_ids", qsv)
		}
	}

	openshiftVersionQ := o.OpenshiftVersion
	if openshiftVersionQ != "" {
		qs.Set("openshift_version", openshiftVersionQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetFeatureSupportsURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetFeatureSupportsURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetFeatureSupportsURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetFeatureSupportsURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetFeatureSupportsURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetFeatureSupportsURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
